version: '3'
services:
  echo-db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
    volumes:
      - mysql-data-echo:/var/lib/mysql
      - ./db/mysql/config/echo-db.cnf:/etc/mysql/conf.d/echo-db.cnf
    ports:
      - "3307:3306"
  app:
    build: .
    ports:
      - 8081:8081
    volumes:
      - ./ap/src:/go/src
    tty: true
    depends_on: 
      - "echo-db"
volumes:
  mysql-data-echo:

    